# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'vs2015-win2012r2'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.12.0'
  displayName: 'Install Node.js'

## THE AGENT HAS ADMIN BUT THE COMMENTED SCIPT SAYS IT DOESN'T. WHY MS WHY?

#- script: |
#    ECHO Lets make npm static as well
#    ECHO Installing npm-windows-upgrade
#    CALL npm install --global --production npm-windows-upgrade
#    ECHO Installing npm
#    CALL npm-windows-upgrade --no-spinner --no-prompt --npm-version 6.4.1
#  displayName: 'Install npm 6.4.1'

- script: |
    CALL npm config set msvs_version 2015
    CALL npm install
  displayName: 'npm install'

- script: |
    CALL npm test
  displayName: 'npm test'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFile: "**/test-*.xml"
