# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'vs2015-win2012r2'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    ECHO Appearently the Agent has an older version of npm, thus causing the install script to stop after preinstall
    ECHO Installing npm-windows-upgrade
    npm install --global --production npm-windows-upgrade
    ECHO Installing npm
    npm-windows-upgrade --no-spinner --no-prompt --npm-version 6.4.1
  displayName: 'Install npm 6.4.1'

- script: |
    npm config set msvs_version 2015
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFile: "**/test-*.xml"
