# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'vs2015-win2012r2'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm config set msvs_version 2015
    npm install
    npm test
  displayName: 'npm install && npm test'
- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFile: "**/test-*.xml"
